#Datosestaticos
listaServicios = [
                "Aplicacion de pestañas",
                "Aplicacion de uñas",
                "Retiros (pestañas,uñas)",
                "Macroblading",
                "Manicure",
                "Pedicure",
                "Aplicacion de gelish",
                "Masajes",
                "Depilacion con cera",
                "Alisado permanente"]
listaPrecios = [
"$450.00",
"$320.00",
"$200.00",
"$1000.00",
"$230.00",
"$350.00",
"$200.00",
"$700.00",
"200.00",
"$400.00"
]

listaProductos=[
            "Perfumes",
            "Sombras para ojos",
            "Bolsas",
            "Shampoo",
            "Cremas",   
            "Joyeria",
            "Relojes",
            "Plancha para cabello",
            "Secadora de cabello",
            "Tenasas para risos",
            "Protectores de cabello",
            "Esponjas para maquillaje ",
            "Esmaltes",
            "Acrilicos",
            "Gelish",
            "Lampara para uñas",
            "Pinceles",
            "Labiales",
            "Mascara de pestañas",
            "Protector solar",
            ]

montoProductos=[
"500.00",
"350.00",
"600.00",
"55.00",
"45.00",
"300.00",
"350.00",
"400.00",
"350.00",
"400.00",
"150.00",
"100.00",
"150.00",
"250.00",
"250.00",
"500.00",
"150.00",
"200.00",
"100.00",
"150.00",
]

listaDiseños=[
                "Recubrimiento Acrílico",
                "Vitamina con calcio para tus uñas",
                "Esmalte en gel semi permanente",
                "Uñas acrílicas con Tip",
                "Uñas acrílicas Esculturales",
                "Retoque y mantenimiento de uñas acrílicas",
                "Relojes",
                "Decoración de uñas",
                "Retiro de acrílico",
                "Retiro de Esmalte en Gel semi permanente",
                "Vitamina con calcio para tus uñas",
                "-----Pestañas-----",
                "Esmalte Tradicional ",
                "Efecto Natural",
                "Efecto Cásico",
                "Efecto Glam",
                "Técnica Híbrida",
                "Volumen ruso",
                "-----Depilacion-----",
                "Facial",
                "Piernas",
                "Ceja",
                "Axila",
                "Brazos",
]
   


listaTrabajadores=[
                    "-----Trabajadores-----",
                    "Rosario Barrios García",
                    "Emilio Jiménez Rodríguez",
                    "Elena Flores López",
                    "Diego Reyes Martínez",
                    "Socorro Ortiz González",
                    "Santiago Aguilar Pérez",
                    "Valeria León Ramírez",
                    "Rodolfo Paredes Hernández",
                    "Silvia Cordero Silva",
                    "Fernando Valencia Torres"
]
 

listaClientes=[
                "Emma García",
                "Miguel Rodríguez",
                "Noah López",
                "Jorge Martínez",
                "Liam González",
                "Rafael Pérez",
                "Olivia Ramírez",
                "Feliciano Hernández",
                "Ava Silva",
                "Ariel Torres",
                "Isabella Díaz",
                "Nicolás Cruz",
                "Sophia Morales",
                "Benito Castro",
                "Mia Gómez",
                "Antonio Vargas"
                "Charlotte Mendoza",
                "Simón Ruiz",
                "Amelia Romero",
                "Eduardo Medina",
                "Harper Ríos",
                "Roberto Navarro",
                "Evelyn Sánchez",
                "Isidoro Castillo",
                "Abigail Ezpinoza",
                "Mauricio García",
                "Emily Rodríguez",
                "Kevin García",
                "Elizabeth Rodríguez",
                "Leister López",]


listaCombos=[
            "Pestañas y Sombra de ojos",
            "Macroblading y Plancha para cabello",
            "Aplicacion de gelish y depilacion de ceja",
            "Masaje y bolsa"
            "Alisado permanente y shapoo",
            "Manicure y Perfume",
            "Aplicacion de uñas y collar",
            "Tensas para risos y crema",
            "Esponjas para maquillaje y Retiro de uñas",
            "Secadora de cabello y protector solar",
            "Aplicacion de uñas y esmaltes",
            "Macroblading y Acrilicos",
            "Lampara de uñas y acrilicos",
            "Depilacion de Axilas y Mascara de pestañas",
            "Pedicure y Masaje",
            "Aplicacion de gelish y Lampara para uñas",
            "Protector solar y Bolsa",
            "Masaje y Aplicacion de gelish",
            "Manicure y Aplicacion de uñas",
            "Pedicure y Aretes"]

costoCombos=[
"600.00",
"950.00",
"250.00",
"950.00",
"350.00",
"600.00",
"650.00",
"300.00",
"250.00",
"450.00",
"500.00",
"1,125.00",
"675.00",
"270.00",
"945.00",
"630.00",
"675.00",
"810.00",
"495.00",
"585.00"]


