#Datosestaticos
def listaServicios():
    print("-----Servicios-----")
    print("1. Perfumes")
    print("2. Cosmeticos")
    print("3. Bolsas")
    print("4. Shapoo")
    print("5. Cremas")
    print("6. Joyeria")
    print("7. Relojes")
    print("8. ")
    print("9. Verduras")
    print("10. Vinos")

def listarProductos():
    print("-----Productos-----")
    print("1. Perfumes")
    print("2. Cosmeticos")
    print("3. Bolsas")
    print("4. Shapoo")
    print("5. Cremas")
    print("6. Joyeria")
    print("7. Relojes")
    print("8. ")
    print("9. Verduras")
    print("10. Vinos")
def listaDiseños():
    print("-----Productos-----")
    print("1. Perfumes")
    print("2. Cosmeticos")
    print("3. Bolsas")
    print("4. Shapoo")
    print("5. Cremas")
    print("6. Joyeria")
    print("7. Relojes")
    print("8. ")
    print("9. Verduras")
    print("10. Vinos")